### ISSUE TITLE
Bitsail flink on yarn demo not work 'Cannot find library'

### ISSUE THREAD

**Issue by numbernumberone** [bytedance/bitsail#177]
submit task to centos7 with yarn cluster.

error log with `embedded flink-client.log`
```
	"job":{
		"common":{
			"instance_id":3124,
			"job_name":"BitSail_fake_to_print_test",
			"job_id":312,
			"user_name":"test"
		},
		"reader":{
			"partition":"date=20180101",
			"db_name":"bitsail",
			"source_engine":"hive",
			"columns":[
				{
					"name":"id",
					"index":0,
					"type":"int"
				}
			],
			"metastore_properties":"{\"hive.metastore.uris\":\"<Your-Hive-Metastore-Address>\"}",
			"class":"com.bytedance.bitsail.connector.legacy.hive.source.HiveInputFormat",
			"table_name":"test_opensource",
			"reader_parallelism_num":2
		},
		"writer":{
			"class":"com.bytedance.bitsail.connector.legacy.print.sink.PrintSink"
		}
	}
}
2022-11-15 14:52:29,460 INFO  com.bytedance.bitsail.base.statistics.VMInfo                 [] - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-11-15 14:52:29,485 INFO  com.bytedance.bitsail.core.Engine                            [] - the machine info  => 

	osInfo:	Oracle Corporation 1.8 25.161-b12
	jvmInfo:	Linux amd64 3.10.0-957.el7.x86_64
	cpu num:	8

	totalPhysicalMemory:	-0.00G
	freePhysicalMemory:	-0.00G
	maxFileDescriptorCount:	-1
	currentOpenFileDescriptorCount:	-1

	GC Names	[PS MarkSweep, PS Scavenge]

	MEMORY_NAME                    | allocation_size                | init_size                      
	PS Eden Space                  | 1,304.00MB                     | 63.00MB                        
	Code Cache                     | 240.00MB                       | 2.44MB                         
	Compressed Class Space         | 1,024.00MB                     | 0.00MB                         
	PS Survivor Space              | 10.00MB                        | 10.00MB                        
	PS Old Gen                     | 2,648.00MB                     | 167.00MB                       
	Metaspace                      | -0.00MB                        | 0.00MB                         


2022-11-15 14:52:30,338 INFO  com.bytedance.bitsail.base.packages.PluginManager            [] - Plugin manager root plugin dir = /home/hdfs/blackjoker/bitsail-master/bitsail-dist/target/bitsail-dist-0.1.0-SNAPSHOT-bin/bitsail-archive-0.1.0-SNAPSHOT/./libs.
2022-11-15 14:52:30,370 INFO  com.bytedance.bitsail.core.reader.DataReaderBuilderFactory   [] - Reader class name is com.bytedance.bitsail.connector.legacy.hive.source.HiveInputFormat
2022-11-15 14:52:30,371 ERROR com.bytedance.bitsail.core.reader.DataReaderBuilderFactory   [] - failed to create reader DAG builder
2022-11-15 14:52:30,372 ERROR com.bytedance.bitsail.core.Engine                            [] - 

The cause of the job failure maybe due to:
java.lang.RuntimeException: java.lang.RuntimeException: Cannot find library: /home/hdfs/blackjoker/bitsail-master/bitsail-dist/target/bitsail-dist-0.1.0-SNAPSHOT-bin/bitsail-archive-0.1.0-SNAPSHOT/./libs/connectors/bitsail-connector-hive-<unknown>.jar
	at com.bytedance.bitsail.core.reader.DataReaderBuilderFactory.lambda$getDataReaderDAGBuilderList$0(DataReaderBuilderFactory.java:53)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.bytedance.bitsail.core.reader.DataReaderBuilderFactory.getDataReaderDAGBuilderList(DataReaderBuilderFactory.java:56)
	at com.bytedance.bitsail.core.job.UnificationJob.prepare(UnificationJob.java:102)
	at com.bytedance.bitsail.core.job.UnificationJob.start(UnificationJob.java:89)
	at com.bytedance.bitsail.core.Engine.run(Engine.java:85)
	at com.bytedance.bitsail.core.Engine.start(Engine.java:68)
	at com.bytedance.bitsail.core.Engine.main(Engine.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:319)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:219)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:147)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:765)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:233)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:992)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1070)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
	at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1070)
Caused by: java.lang.RuntimeException: Cannot find library: /home/hdfs/blackjoker/bitsail-master/bitsail-dist/target/bitsail-dist-0.1.0-SNAPSHOT-bin/bitsail-archive-0.1.0-SNAPSHOT/./libs/connectors/bitsail-connector-hive-<unknown>.jar
	at com.bytedance.bitsail.base.packages.PluginManager.getPluginLibraries(PluginManager.java:176)
	at com.bytedance.bitsail.base.packages.PluginManager.getPluginLibs(PluginManager.java:187)
	at com.bytedance.bitsail.base.packages.PackageManager.retrieveClassLoader(PackageManager.java:154)
	at com.bytedance.bitsail.base.packages.PackageManager.loadDynamicLibrary(PackageManager.java:122)
	at com.bytedance.bitsail.core.reader.DataReaderBuilderFactory.getReaderClass(DataReaderBuilderFactory.java:82)
	at com.bytedance.bitsail.core.reader.DataReaderBuilderFactory.getDataReaderDAGBuilder(DataReaderBuilderFactory.java:62)
	at com.bytedance.bitsail.core.reader.DataReaderBuilderFactory.lambda$getDataReaderDAGBuilderList$0(DataReaderBuilderFactory.java:50)
	... 29 more

2022-11-15 14:52:30,373 INFO  com.bytedance.bitsail.flink.core.execution.FlinkExecutionEnviron [] - Flink job start terminal.
```

**Comment by numbernumberone** [comment]
pluginName2Plugin is 
```
"bitsail-connector-legacy-streamingfile":{"classNames":["com.bytedance.bitsail.connector.legacy.streamingfile.sink.FileSystemSinkFunctionDAGBuilder"],"libs":["bitsail-connector-streamingfile-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-streamingfile"},"bitsail-connector-legacy-redis":{"classNames":["com.bytedance.bitsail.connector.legacy.redis.source.RedisOutputFormat"],"libs":["bitsail-connector-redis-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-redis"},"bitsail-connector-unified-doris":{"classNames":["com.bytedance.bitsail.connector.doris.sink.DorisSink"],"libs":["bitsail-connector-doris-<unknown>.jar"],"pluginName":"bitsail-connector-unified-doris"},"bitsail-connector-unified-elasticsearch":{"classNames":["com.bytedance.bitsail.connector.elasticsearch.sink.ElasticsearchSink"],"libs":["connector-elasticsearch-<unknown>.jar"],"pluginName":"bitsail-connector-unified-elasticsearch"},"bitsail-connector-legacy-jdbc":{"classNames":["com.bytedance.bitsail.connector.legacy.jdbc.sink.JDBCOutputFormat","com.bytedance.bitsail.connector.legacy.jdbc.source.JDBCInputFormat","com.bytedance.bitsail.connector.legacy.jdbc.sink.PostgresqlOutputFormat","com.bytedance.bitsail.connector.legacy.jdbc.source.PostgresqlInputFormat","com.bytedance.bitsail.connector.legacy.jdbc.sink.SqlServerOutputFormat","com.bytedance.bitsail.connector.legacy.jdbc.source.SqlServerInputFormat","com.bytedance.bitsail.connector.legacy.jdbc.sink.OracleOutputFormat","com.bytedance.bitsail.connector.legacy.jdbc.source.OracleInputFormat"],"libs":["bitsail-connector-jdbc-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-jdbc"},"bitsail-connector-unified-rocketmq":{"classNames":["com.bytedance.bitsail.connector.rocketmq.source.RocketMQSource"],"libs":["connector-rocketmq-<unknown>.jar"],"pluginName":"bitsail-connector-unified-rocketmq"},"bitsail-connector-legacy-hadoop":{"classNames":["com.bytedance.bitsail.connector.hadoop.source.HadoopInputFormat"],"libs":["bitsail-connector-hadoop-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-hadoop"},"bitsail-connector-unified-fake":{"classNames":["com.bytedance.bitsail.connector.fake.source.FakeSource"],"libs":["connector-fake-<unknown>.jar"],"pluginName":"bitsail-connector-unified-fake"},"bitsail-connector-legacy-kafka":{"classNames":["com.bytedance.bitsail.connector.legacy.kafka.source.KafkaSourceFunctionDAGBuilder","com.bytedance.bitsail.connector.legacy.kafka.sink.KafkaOutputFormat"],"libs":["bitsail-connector-kafka-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-kafka"},"bitsail-connector-legacy-mongodb":{"classNames":["com.bytedance.bitsail.connector.legacy.mongodb.source.MongoDBInputFormat","com.bytedance.bitsail.connector.legacy.mongodb.sink.MongoDBOutputFormat"],"libs":["bitsail-connector-mongodb-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-mongodb"},"bitsail-connector-redis":{"classNames":["com.bytedance.bitsail.connector.redis.sink.RedisSink"],"libs":["bitsail-connector-redis-<unknown>.jar"],"pluginName":"bitsail-connector-redis"},"bitsail-connector-legacy-fake":{"classNames":["com.bytedance.bitsail.connector.legacy.fake.source.FakeSource","com.bytedance.bitsail.connector.legacy.fake.source.FakeFlinkSource"],"libs":["bitsail-connector-fake-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-fake"},"bitsail-connector-legacy-hbase":{"classNames":["com.bytedance.bitsail.connector.hbase.source.HBaseInputFormat","com.bytedance.bitsail.connector.hbase.sink.HBaseOutputFormat"],"libs":["bitsail-connector-hbase-<unknown>.jar","bitsail-connector-hadoop-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-hbase"},"bitsail-connector-unified-kudu":{"classNames":["com.bytedance.bitsail.connector.kudu.sink.KuduSink","com.bytedance.bitsail.connector.kudu.source.KuduSource"],"libs":["connector-kudu-<unknown>.jar"],"pluginName":"bitsail-connector-unified-kudu"},"bitsail-connector-legacy-print":{"classNames":["com.bytedance.bitsail.connector.legacy.print.sink.PrintSink"],"libs":["bitsail-connector-print-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-print"},"bitsail-connector-legacy-ftp":{"classNames":["com.bytedance.bitsail.connector.legacy.ftp.source.FtpInputFormat"],"libs":["bitsail-connector-ftp-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-ftp"},"bitsail-connector-legacy-hive":{"classNames":["com.bytedance.bitsail.connector.legacy.hive.source.HiveInputFormat","com.bytedance.bitsail.connector.legacy.hive.sink.HiveOutputFormat"],"libs":["bitsail-connector-hive-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-hive"},"bitsail-connector-legacy-hudi":{"classNames":["com.bytedance.bitsail.connector.legacy.hudi.dag.HudiSinkFunctionDAGBuilder","com.bytedance.bitsail.connector.legacy.hudi.dag.HudiSourceFunctionDAGBuilder","com.bytedance.bitsail.connector.legacy.hudi.dag.HudiCompactSinkDAGBuilder","com.bytedance.bitsail.connector.legacy.hudi.dag.HudiCompactSourceDAGBuilder"],"libs":["bitsail-connector-hudi-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-hudi"},"bitsail-connector-legacy-larksheet":{"classNames":["com.bytedance.bitsail.connector.legacy.larksheet.source.LarkSheetInputFormat"],"libs":["bitsail-connector-larksheet-<unknown>.jar"],"pluginName":"bitsail-connector-legacy-larksheet"}}. 
```

**Comment by numbernumberone** [comment]
@hk-lrzy hello
### my problem environment is centos7
Because the code is not pulled through git for network reasons. 
code download ZIP from github.
1. Execute the following command on centos 

```shell
sh build.sh 
```
2. result is ：
bitsail-core.jar not  exists  `.dataleap.bitsail.version.properties`
<img width="646" alt="image" src="https://user-images.githubusercontent.com/17960477/201880831-32b9667a-a74f-4f98-80e2-7c337ee53e87.png">

### my local normal environment

1. Execute the following command on macos m1
```shell
sh build.sh 
```
2. result is :
exists `.dataleap.bitsail.version.properties`
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/17960477/201881528-d8f1dfb8-65c5-4873-8b6a-a3346a29cf55.png">



### resolve
upload `bitsail-core.jar` to centos ?

**Comment by numbernumberone** [comment]
@hk-lrzy 
```shell
[root@VM_0_17_centos ~]# mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /root/black/apache-maven-3.6.3
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/local/jdk/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.el7.x86_64", arch: "amd64", family: "unix"
```

**Comment by numbernumberone** [comment]
@hk-lrzy This is OK, but I wonder why there is no version file `.dataleap.bitsail.version.properties` for the downloaded code

**Comment by numbernumberone** [comment]
@hk-lrzy OK, the problem has been solved. Thank you very much

**Comment by BlockLiu** [comment]
Issue has been fixed by [PR-443](https://github.com/bytedance/bitsail/pull/423)
